/*
    This component is primarily created to handle the input functionality.
*/

function Input({value}){
    return(
        <>
            <div>
                <input value={value} type="text" readOnly />  {/* Which button is clicked, it's functionality and 
                                                                value generated by it will be displayed on the input 
                                                                field of calculator. 
                                                                 */}
            </div>
        </>
    )
}

export default Input